//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YA.Localization.MessageLocalize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YA.Localization.MessageLocalize.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete operation failed..
        /// </summary>
        public static string DeleteField {
            get {
                return ResourceManager.GetString("DeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete operation failed in some cases..
        /// </summary>
        public static string DeletesField {
            get {
                return ResourceManager.GetString("DeletesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion was successful..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is available..
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was not performed..
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed..
        /// </summary>
        public static string FindField {
            get {
                return ResourceManager.GetString("FindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search was successful..
        /// </summary>
        public static string FindSuccess {
            get {
                return ResourceManager.GetString("FindSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed..
        /// </summary>
        public static string InsertField {
            get {
                return ResourceManager.GetString("InsertField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successful..
        /// </summary>
        public static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not allowed.
        /// </summary>
        public static string Limited {
            get {
                return ResourceManager.GetString("Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is invalid..
        /// </summary>
        public static string LoginField {
            get {
                return ResourceManager.GetString("LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has expired..
        /// </summary>
        public static string LoginFieldAccess {
            get {
                return ResourceManager.GetString("LoginFieldAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login was successful..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {} Not available.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update operation failed..
        /// </summary>
        public static string UpdateField {
            get {
                return ResourceManager.GetString("UpdateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update operation was completed successfully..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
